# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
notifications:
  email: false
julia:
  - 1.5
  - nightly
os:
  - linux
  - osx
  - windows
arch:
  - x64
branches:
  only: master
cache:
  directories:
    - ~/.julia/artifacts
matrix:
  allow_failures:
    - julia: nightly
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

## uncomment following lines to deploy documentation
jobs:
   include:
     - stage: Documentation
       julia: 1.5
       os: linux
       script:
         - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
         - julia --project=docs docs/make.jl
       after_success: skip